-- ==========================================================
-- SCRIPT DE CONFIGURACIÓN Y POLÍTICAS RLS PARA SUPABASE
-- Proyecto: Catálogo Digital Supermarket (Tame, Arauca)
-- ==========================================================

-- 1. TABLA: productos
CREATE TABLE IF NOT EXISTS public.productos (
    id_producto BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_producto TEXT NOT NULL,
    presentacion TEXT,
    precio NUMERIC NOT NULL,
    imagen_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Políticas RLS para productos
ALTER TABLE public.productos ENABLE ROW LEVEL SECURITY;

-- Permitir lectura pública a cualquier visitante
CREATE POLICY "Permitir lectura productos" 
ON public.productos FOR SELECT 
TO anon, authenticated 
USING (true);

-- Permitir agregar nuevos productos desde la app web
CREATE POLICY "Permitir insercion productos" 
ON public.productos FOR INSERT 
TO anon, authenticated 
WITH CHECK (true);

-- Permitir eliminar productos (para limpiar duplicados o productos obsoletos)
CREATE POLICY "Permitir eliminar productos" 
ON public.productos FOR DELETE 
TO anon, authenticated 
USING (true);

-- Permitir actualizar productos
CREATE POLICY "Permitir actualizar productos" 
ON public.productos FOR UPDATE 
TO anon, authenticated 
USING (true);


-- 2. TABLA: contactos
CREATE TABLE IF NOT EXISTS public.contactos (
    id_contacto BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_completo TEXT NOT NULL,
    correo_electronico TEXT NOT NULL,
    asunto TEXT NOT NULL,
    mensaje TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Políticas RLS para contactos
ALTER TABLE public.contactos ENABLE ROW LEVEL SECURITY;

-- Permitir envíos en el formulario de contactos
CREATE POLICY "Permitir envios contactos" 
ON public.contactos FOR INSERT 
TO anon, authenticated 
WITH CHECK (true);

-- Permitir lectura de contactos
CREATE POLICY "Permitir lectura contactos" 
ON public.contactos FOR SELECT 
TO anon, authenticated 
USING (true);

-- Permitir eliminar contactos
CREATE POLICY "Permitir eliminar contactos" 
ON public.contactos FOR DELETE 
TO anon, authenticated 
USING (true);

